"""Moonshot v2 — Feature Registry.

Defines every feature used by the system: name, compute function reference,
history requirements, data sources, availability tier, neutral fill value,
and category.
"""

FEATURE_REGISTRY = {
    # ── Price Action (6) ────────────────────────────────────────────────────
    "price_vs_52w_high": {
        "fn": "_compute_price_vs_52w_high",
        "bars": 2190,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.5,
        "category": "core",
    },
    "price_vs_52w_low": {
        "fn": "_compute_price_vs_52w_low",
        "bars": 2190,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    "momentum_4w": {
        "fn": "_compute_momentum_4w",
        "bars": 168,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.0,
        "category": "core",
    },
    "momentum_8w": {
        "fn": "_compute_momentum_8w",
        "bars": 336,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.0,
        "category": "core",
    },
    "bb_squeeze_pct": {
        "fn": "_compute_bb_squeeze_pct",
        "bars": 120,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    "bb_position": {
        "fn": "_compute_bb_position",
        "bars": 20,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.5,
        "category": "core",
    },
    # ── Volume (5) ──────────────────────────────────────────────────────────
    "volume_ratio_7d": {
        "fn": "_compute_volume_ratio_7d",
        "bars": 180,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    "volume_ratio_3d": {
        "fn": "_compute_volume_ratio_3d",
        "bars": 84,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    "obv_slope": {
        "fn": "_compute_obv_slope",
        "bars": 14,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.0,
        "category": "core",
    },
    "volume_spike": {
        "fn": "_compute_volume_spike",
        "bars": 14,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    "volume_trend": {
        "fn": "_compute_volume_trend",
        "bars": 30,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.0,
        "category": "core",
    },
    # ── Volatility (4) ──────────────────────────────────────────────────────
    "atr_percentile": {
        "fn": "_compute_atr_percentile",
        "bars": 540,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 50.0,
        "category": "core",
    },
    "atr_compression": {
        "fn": "_compute_atr_compression",
        "bars": 168,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    "high_low_range_pct": {
        "fn": "_compute_high_low_range_pct",
        "bars": 1,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.02,
        "category": "core",
    },
    "realized_vol_ratio": {
        "fn": "_compute_realized_vol_ratio",
        "bars": 180,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 1.0,
        "category": "core",
    },
    # ── Price Structure (5) ─────────────────────────────────────────────────
    "distance_from_support": {
        "fn": "_compute_distance_from_support",
        "bars": 180,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.05,
        "category": "core",
    },
    "distance_from_resistance": {
        "fn": "_compute_distance_from_resistance",
        "bars": 180,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.05,
        "category": "core",
    },
    "consec_down_bars": {
        "fn": "_compute_consec_down_bars",
        "bars": 50,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0,
        "category": "core",
    },
    "consec_up_bars": {
        "fn": "_compute_consec_up_bars",
        "bars": 50,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0,
        "category": "core",
    },
    "higher_highs": {
        "fn": "_compute_higher_highs",
        "bars": 14,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 7,
        "category": "core",
    },
    # ── Market Regime (3 — BTC candles) ─────────────────────────────────────
    "btc_30d_return": {
        "fn": "_compute_btc_30d_return",
        "bars": 180,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 0.0,
        "category": "core",
    },
    "btc_vol_percentile": {
        "fn": "_compute_btc_vol_percentile",
        "bars": 540,
        "sources": ["candles"],
        "availability": "all",
        "neutral": 50.0,
        "category": "core",
    },
    "market_breadth": {
        "fn": "_compute_market_breadth",
        "bars": 180,
        "sources": ["candles", "open_interest"],
        "availability": "all",
        "neutral": 0.5,
        "category": "core",
    },
    # ── Coin Metadata (2) ───────────────────────────────────────────────────
    "days_since_listing": {
        "fn": "_compute_days_since_listing",
        "bars": 0,
        "sources": ["coins"],
        "availability": "all",
        "neutral": 365,
        "category": "core",
    },
    "is_new_listing": {
        "fn": "_compute_is_new_listing",
        "bars": 0,
        "sources": ["coins"],
        "availability": "all",
        "neutral": 0,
        "category": "core",
    },
    # ── Funding Rate (3) ────────────────────────────────────────────────────
    "funding_rate_current": {
        "fn": "_compute_funding_rate_current",
        "bars": 0,
        "sources": ["funding_rates"],
        "availability": "extended",
        "neutral": 0.0,
        "category": "extended",
    },
    "funding_rate_7d_avg": {
        "fn": "_compute_funding_rate_7d_avg",
        "bars": 0,
        "sources": ["funding_rates"],
        "availability": "extended",
        "neutral": 0.0,
        "category": "extended",
    },
    "funding_rate_extreme": {
        "fn": "_compute_funding_rate_extreme",
        "bars": 0,
        "sources": ["funding_rates"],
        "availability": "extended",
        "neutral": 0,
        "category": "extended",
    },
    # ── Open Interest (4) ───────────────────────────────────────────────────
    "oi_change_24h": {
        "fn": "_compute_oi_change_24h",
        "bars": 0,
        "sources": ["open_interest"],
        "availability": "extended",
        "neutral": 0.0,
        "category": "extended",
    },
    "oi_change_7d": {
        "fn": "_compute_oi_change_7d",
        "bars": 0,
        "sources": ["open_interest"],
        "availability": "extended",
        "neutral": 0.0,
        "category": "extended",
    },
    "oi_price_divergence": {
        "fn": "_compute_oi_price_divergence",
        "bars": 42,
        "sources": ["open_interest", "candles"],
        "availability": "extended",
        "neutral": 0,
        "category": "extended",
    },
    "oi_percentile_90d": {
        "fn": "_compute_oi_percentile_90d",
        "bars": 0,
        "sources": ["open_interest"],
        "availability": "extended",
        "neutral": 50.0,
        "category": "extended",
    },
    # ── Mark Price (1) ──────────────────────────────────────────────────────
    "mark_index_spread": {
        "fn": "_compute_mark_index_spread",
        "bars": 0,
        "sources": ["mark_prices"],
        "availability": "extended",
        "neutral": 0.0,
        "category": "extended",
    },
    # ── Ticker (4) ──────────────────────────────────────────────────────────
    "price_vs_24h_high": {
        "fn": "_compute_price_vs_24h_high",
        "bars": 0,
        "sources": ["tickers_24h"],
        "availability": "extended",
        "neutral": 0.95,
        "category": "extended",
    },
    "price_vs_24h_low": {
        "fn": "_compute_price_vs_24h_low",
        "bars": 0,
        "sources": ["tickers_24h"],
        "availability": "extended",
        "neutral": 1.05,
        "category": "extended",
    },
    "vol_24h_vs_7d_avg": {
        "fn": "_compute_vol_24h_vs_7d_avg",
        "bars": 0,
        "sources": ["tickers_24h"],
        "availability": "extended",
        "neutral": 1.0,
        "category": "extended",
    },
    "price_change_24h_pct": {
        "fn": "_compute_price_change_24h_pct",
        "bars": 0,
        "sources": ["tickers_24h"],
        "availability": "extended",
        "neutral": 0.0,
        "category": "extended",
    },
    # ── Social Features (13) ────────────────────────────────────────────────
    "fear_greed_score": {
        "fn": "_compute_fear_greed_score",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 50.0,
        "category": "social",
    },
    "fear_greed_7d_change": {
        "fn": "_compute_fear_greed_7d_change",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0.0,
        "category": "social",
    },
    "is_coingecko_trending": {
        "fn": "_compute_is_coingecko_trending",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "trending_rank": {
        "fn": "_compute_trending_rank",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "hours_on_trending": {
        "fn": "_compute_hours_on_trending",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "news_mentions_24h": {
        "fn": "_compute_news_mentions_24h",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "news_mentions_7d_avg": {
        "fn": "_compute_news_mentions_7d_avg",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "news_velocity_ratio": {
        "fn": "_compute_news_velocity_ratio",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 1.0,
        "category": "social",
    },
    "reddit_mentions_24h": {
        "fn": "_compute_reddit_mentions_24h",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "reddit_score_24h": {
        "fn": "_compute_reddit_score_24h",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "reddit_velocity_ratio": {
        "fn": "_compute_reddit_velocity_ratio",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 1.0,
        "category": "social",
    },
    "github_commits_7d": {
        "fn": "_compute_github_commits_7d",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 0,
        "category": "social",
    },
    "github_commit_spike": {
        "fn": "_compute_github_commit_spike",
        "bars": 0,
        "sources": ["social_events"],
        "availability": "social",
        "neutral": 1.0,
        "category": "social",
    },
}


def get_feature_names(category=None):
    """Return sorted list of feature names, optionally filtered by category."""
    if category is None:
        return sorted(FEATURE_REGISTRY.keys())
    return sorted(k for k, v in FEATURE_REGISTRY.items() if v["category"] == category)


def get_neutral_fill():
    """Return dict of feature_name -> neutral fill value."""
    return {k: v["neutral"] for k, v in FEATURE_REGISTRY.items()}
